"""Incubating Python binding for coding-agent durability protocol v1."""

from .errors import (
    AuthorizationError,
    CanceledTurnError,
    ContractValidationError,
    InvalidTransitionError,
    OperationConflictError,
    ProtocolError,
    RejectedOperationError,
    RevokedAuthorityError,
    StaleAuthorityError,
)
from .json_adapter import (
    MAX_JSON_DEPTH,
    MAX_JSON_DOCUMENT_BYTES,
    SchemaCorpus,
    loads_strict,
)
from .kernel import ProtocolKernel
from .models import (
    SCHEMA_VERSION,
    AuthorityStatus,
    DestinationCapability,
    Disposition,
    EffectOutcome,
    ExecutorAuthorization,
    ExecutorIdentity,
    Lifecycle,
    LogicalIdentity,
    Operation,
    OperationRequest,
    OwnerCapability,
    ProcessExecutorIdentity,
    ProviderExecutorIdentity,
    Receipt,
    Rejection,
    RejectionType,
    StopTarget,
    TransitionRecord,
    TransitionResult,
    TurnState,
    capability_digest,
    mint_owner_capability,
)

__all__ = [
    "MAX_JSON_DEPTH",
    "MAX_JSON_DOCUMENT_BYTES",
    "SCHEMA_VERSION",
    "AuthorityStatus",
    "AuthorizationError",
    "CanceledTurnError",
    "ContractValidationError",
    "DestinationCapability",
    "Disposition",
    "EffectOutcome",
    "ExecutorAuthorization",
    "ExecutorIdentity",
    "InvalidTransitionError",
    "Lifecycle",
    "LogicalIdentity",
    "Operation",
    "OperationConflictError",
    "OperationRequest",
    "OwnerCapability",
    "ProcessExecutorIdentity",
    "ProtocolError",
    "ProtocolKernel",
    "ProviderExecutorIdentity",
    "Receipt",
    "RejectedOperationError",
    "Rejection",
    "RejectionType",
    "RevokedAuthorityError",
    "SchemaCorpus",
    "StaleAuthorityError",
    "StopTarget",
    "TransitionRecord",
    "TransitionResult",
    "TurnState",
    "capability_digest",
    "loads_strict",
    "mint_owner_capability",
]
